language: python
sudo: false
python:

  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - coverage run
  - python test.py -v # or py.test for Python versions 3.5 and below
after_success:
  - coveralls
